nelmio_api_doc:
  areas:
    path_patterns:
      - ^/api/
  documentation:
    servers:
      - url: http://localhost
        description: API over HTTPS
    info:
      title: My Sudoku App
      description: This is a pet-project.
      version: 1.0.0