app.swagger:
    path: /api/openapi.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

controllers:
    resource:
        path: ../src/Interface/Controller/
        namespace: App\Interface\Controller
    type: attribute
